[env:waveshare_esp32_s3_eth]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Specific hardware configuration for the 16MB Flash / 8MB PSRAM model
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

; Required flags for PSRAM and Serial Monitor via USB
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200


lib_deps =
    milesburton/DallasTemperature @ ^3.9.1    ; Temp Sensors
    bogde/HX711 @ ^0.7.5                       ; Load Cells
    mandulaj/PZEM-004T-v30 @ ^1.1.2            ; Power Monitoring
